trigger: none 

pr: none 

variables:
  vmImage: 'ubuntu-16.04'
  location: eastus
  nodeCount: 3
  nodeSize: Standard_DS2_v2
  # define 3 more variables: kv, aks and rg in the pipeline UI definition

stages:
- stage: CreateAKSCluster
  displayName: CreateAKSCluster
  jobs:
  - job: CreateAKSCluster
    pool:
      vmImage: $(vmImage)
    steps:
    - task: AzureKeyVault@1
      displayName: 'Get secrets from Key Vault'
      inputs:
        azureSubscription: keyvault
        KeyVaultName: $(kv)
        SecretsFilter: 'subscriptionId,spId,spSecret,spTenantId'
    - task: Bash@3
      displayName: 'create rg and aks'
      inputs:
        targetType: filePath
        filePath: './create-aks-cluster.sh'
        failOnStderr: true
      env:
          LOCATION: $(location)
          NODE_COUNT: $(nodeCount)
          NODE_SIZE: $(nodeSize)
          SUBSCRIPTION_ID: $(subscriptionId)
          SP_ID: $(spId)
          SP_SECRET: $(spSecret)
          SP_TENANT_ID: $(spTenantId)
          AKS: $(aks)
          RG: $(rg)
- stage: AzureTests
  displayName: AzureTests
  jobs:
  - job: AzureTests
    pool:
      vmImage: $(vmImage)
    steps:
    - task: AzureKeyVault@1
      displayName: 'Get secrets from Key Vault'
      inputs:
        azureSubscription: keyvault
        KeyVaultName: $(kv)
        SecretsFilter: 'subscriptionId,spId,spSecret,spTenantId'
    - task: Bash@3
      displayName: 'test azure infra'
      inputs:
        targetType: filePath
        filePath: './test-azure-infra.sh'
        failOnStderr: true
      env:
          LOCATION: $(location)
          NODE_COUNT: $(nodeCount)
          NODE_SIZE: $(nodeSize)
          SUBSCRIPTION_ID: $(subscriptionId)
          SP_ID: $(spId)
          SP_SECRET: $(spSecret)
          SP_TENANT_ID: $(spTenantId)
          AKS: $(aks)
          RG: $(rg)
